[package]
name = "zfi-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
fatfs = "0.3"
gpt = "3.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
zfi-testing-macros = { path = "../testing-macros" }
