name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Add UEFI targets
      run: |
        rustup target add aarch64-unknown-uefi i686-unknown-uefi x86_64-unknown-uefi
    - name: Check code styles
      run: cargo fmt --check
    - name: Run Clippy
      run: cargo clippy --workspace -- -D warnings
    - name: Build for aarch64-unknown-uefi
      run: cargo build --target aarch64-unknown-uefi
    - name: Build for i686-unknown-uefi
      run: cargo build --target i686-unknown-uefi
    - name: Build for x86_64-unknown-uefi
      run: cargo build --target x86_64-unknown-uefi
